Repository luanemanuel/focus_on_it, pull requests merged in 2023-01, with the labels that each got.

#2 Focus on it example app
  .gitignore
  example/.gitignore
  example/.metadata
  example/README.md
  example/analysis_options.yaml
  example/lib/main.dart
  example/pubspec.lock
  example/pubspec.yaml
Labels: type: documentation, priority: critical

#3 Sanity test para o focus_on_it
  test/focus_on_it_test.dart
Labels: type: feature request, priority: medium

#4 Documentation
  CHANGELOG.md
  README.md
  assets/focus_on_it.png
  example/README.md
  example/lib/main.dart
  lib/focus_on_it.dart
  pubspec.yaml
Labels: type: documentation, priority: high

#11 Downgrade do dart da 2.18.6 para 2.12.0
  CHANGELOG.md
  analysis_options.yaml
  example/lib/main.dart
  example/pubspec.lock
  example/pubspec.yaml
  lib/focus_on_it.dart
  pubspec.yaml
Labels: type: bug, priority: critical

#19 Ajustar documentação do onFocus e onUnfocous
  CHANGELOG.md
  README.md
  example/lib/main.dart
  lib/focus_on_it.dart
  pubspec.yaml
Labels: type: documentation, priority: high

#23 Pull Request Checker
  .github/workflows/pr_checker.yml
  .github/workflows/test.yml
Labels: priority: medium

#26 Upgrade readme and changelog
  CHANGELOG.md
  README.md
  example/pubspec.lock
  pubspec.yaml
Labels: type: documentation, priority: high
